---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "port-forwarding.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "port-forwarding.serviceAccountName" . }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
      app: {{ template "port-forwarding.name" . }}
      release: {{ .Release.Name }}
  # serviceName: port-forwarding-controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
        app: {{ template "port-forwarding.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - /root/manager
        env:
        - name: ROUTER_URL
          valueFrom:
            secretKeyRef:
              key: ROUTER_URL
              name: {{ template "port-forwarding.fullname" . }}
        - name: ROUTER_USERNAME
          valueFrom:
            secretKeyRef:
              key: ROUTER_USERNAME
              name: {{ template "port-forwarding.fullname" . }}
        - name: ROUTER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ROUTER_PASSWORD
              name: {{ template "port-forwarding.fullname" . }}
        - name: ROUTER_RULE_PREFIX
          valueFrom:
            secretKeyRef:
              key: ROUTER_RULE_PREFIX
              name: {{ template "port-forwarding.fullname" . }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: {{ template "port-forwarding.name" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ template "port-forwarding.serviceAccountName" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
